// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupUserAttachmentInitParameters struct {
}

type GroupUserAttachmentObservation struct {

	// (String)
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type GroupUserAttachmentParameters struct {

	// (String)
	// +crossplane:generate:reference:type=Group
	// +kubebuilder:validation:Optional
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Reference to a Group to populate groupName.
	// +kubebuilder:validation:Optional
	GroupNameRef *v1.Reference `json:"groupNameRef,omitempty" tf:"-"`

	// Selector for a Group to populate groupName.
	// +kubebuilder:validation:Optional
	GroupNameSelector *v1.Selector `json:"groupNameSelector,omitempty" tf:"-"`

	// (String)
	// +crossplane:generate:reference:type=User
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// Reference to a User to populate userName.
	// +kubebuilder:validation:Optional
	UserNameRef *v1.Reference `json:"userNameRef,omitempty" tf:"-"`

	// Selector for a User to populate userName.
	// +kubebuilder:validation:Optional
	UserNameSelector *v1.Selector `json:"userNameSelector,omitempty" tf:"-"`
}

// GroupUserAttachmentSpec defines the desired state of GroupUserAttachment
type GroupUserAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupUserAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupUserAttachmentInitParameters `json:"initProvider,omitempty"`
}

// GroupUserAttachmentStatus defines the observed state of GroupUserAttachment.
type GroupUserAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupUserAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// GroupUserAttachment is the Schema for the GroupUserAttachments API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,minio}
type GroupUserAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GroupUserAttachmentSpec   `json:"spec"`
	Status            GroupUserAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupUserAttachmentList contains a list of GroupUserAttachments
type GroupUserAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupUserAttachment `json:"items"`
}

// Repository type metadata.
var (
	GroupUserAttachment_Kind             = "GroupUserAttachment"
	GroupUserAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupUserAttachment_Kind}.String()
	GroupUserAttachment_KindAPIVersion   = GroupUserAttachment_Kind + "." + CRDGroupVersion.String()
	GroupUserAttachment_GroupVersionKind = CRDGroupVersion.WithKind(GroupUserAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupUserAttachment{}, &GroupUserAttachmentList{})
}
